### ISSUE TITLE
学长你好

### ISSUE THREAD

**Issue by wang-dua** [Xuezhenggdut/Paper_with_code_for_communication_and_network#2]
### 学长你好

> 我是燕山大学信息工程与科学学院的一名硕士生，研究方向是边缘计算。最近阅读了您发表在` _IEEE Transactions on Vehicular Technology_ 上的文章 _"Joint Service Caching and Computation Offloading Scheme Based on Deep Reinforcement Learning in Vehicular Edge Computing Systems"_，我发现它非常有见解，并且与我的研究相关。

> 您是否可以分享与您的研究相关的开源代码？这将严格用于学术交流目的，我向您保证，所有信息将仅用于研究。非常感谢您考虑这一要求。感谢您的时间，期待您的回复。致以最良好的祝愿。
祝好!

> 邮箱: wjxuan22@gmail.com**

### Dear Zheng Xue,

>  I hope this message finds you well. I am a master's student in the School of Information Engineering and Science at Yanshan University (YSU), focusing on edge computing.

> Having recently read your article, Joint Service Caching and Computation Offloading Scheme Based on Deep Reinforcement Learning in Vehicular Edge Computing Systems, published in IEEE Transactions on Vehicular Technology, I found it incredibly insightful and relevant to my research.

> Would it be possible for you to share the open-source code associated with your study? This would be strictly for academic exchange purposes, and I assure you that all information will be used solely for research.

> Your consideration of this request would be greatly appreciated. Thank you for your time, and I look forward to your response. With best wishes! o(^▽^)o

> **Email address**: wjxuan22@gmail.com

**Comment by Xuezhenggdut** [comment]
同学你好，感谢你对本文的关注，可以参考一下这篇论文的代码https://github.com/fangvv/UAV-DDPG，我的程序主要基于该代码修改（环境函数需要根据文中公式编写）。





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Xuezhenggdut/Paper_with_code_for_communication_and_network"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月4日(星期一) 晚上7:52
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Xuezhenggdut/Paper_with_code_for_communication_and_network] 学长你好 (Issue #2)





 
学长你好
  
我是燕山大学信息工程与科学学院的一名硕士生，研究方向是边缘计算。最近阅读了您发表在` IEEE Transactions on Vehicular Technology 上的文章 "Joint Service Caching and Computation Offloading Scheme Based on Deep Reinforcement Learning in Vehicular Edge Computing Systems"，我发现它非常有见解，并且与我的研究相关。
   
您是否可以分享与您的研究相关的开源代码？这将严格用于学术交流目的，我向您保证，所有信息将仅用于研究。非常感谢您考虑这一要求。感谢您的时间，期待您的回复。致以最良好的祝愿。
 祝好!
   
邮箱: ***@***.*****
  
Dear Zheng Xue,
  
I hope this message finds you well. I am a master's student in the School of Information Engineering and Science at Yanshan University (YSU), focusing on edge computing.
   
Having recently read your article, Joint Service Caching and Computation Offloading Scheme Based on Deep Reinforcement Learning in Vehicular Edge Computing Systems, published in IEEE Transactions on Vehicular Technology, I found it incredibly insightful and relevant to my research.
   
Would it be possible for you to share the open-source code associated with your study? This would be strictly for academic exchange purposes, and I assure you that all information will be used solely for research.
   
Your consideration of this request would be greatly appreciated. Thank you for your time, and I look forward to your response. With best wishes! o(^▽^)o
   
Email address: ***@***.***

**Comment by wang-dua** [comment]
多谢学长指点
